// <auto-generated />
namespace assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _141 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_141));
        
        string IMigrationMetadata.Id
        {
            get { return "202301300725239_1.4.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
